### ISSUE TITLE
compile on osx

### ISSUE THREAD

**Issue by antimodular** [joshuajnoble/ofxWiringPi#4]
i know this addon is meant to be used on the raspberry pi.

i do like the idea of being able to program on osx and even run an osx version of the app. this helps to see if all other parts (all non gpio parts) work.

i used the project generator to make a new OF 0.9.0 app that includes this addon.
made sure that header search paths include:
`../../../addons/ofxWiringPi/src`
`../../../addons/ofxWiringPi/include`

and library search paths include:
`../../../addons/ofxWiringPi/lib`

i had to remove all include/ from  #include "include/mcp3002.h" to #include "mcp3002.h" 

now with #include "ofxWiringPi.h" in ofApp.h the app compiles on osx and runs.
great.

BUT when i now start adding this line to the setup routine:
`wiringPiSetup();`

i get this compile error:

```
Undefined symbols for architecture x86_64:
  "_wiringPiSetup", referenced from:
      ofApp::setup() in ofApp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

would you know why?

also does you addon use the latest wiringPi version?
http://wiringpi.com/wiringpi-update-to-2-29/

thanks a bunch.

**Comment by joshuajnoble** [comment]
You'd need to cross-compile the wiringPi library itself for x86_64, right now it's only compiled for RaspPi. And it's not using the newest version yet, but I plan on adding that in this week.
